# DATA CLEANING ON FIFA_21 DATASET

###**Project Overview**

**Introduction:**
This project aims to clean and preprocess the FIFA player dataset, which contains detailed attributes and skills of soccer players.


**Project Background:**
The FIFA dataset contains information on various aspects of soccer players, teams, and information of their matches such as team statistics, and match results.


**Objective:**
The sole objective of this project is to perform data cleaning: handling missing values, removing duplicates, handling inconsistent data, and transforming the data into a suitable format for analysis, visualization and modeling tasks.


**Dataset Description:**
The FIFA dataset consists of 18979 rows and 77 columns, including:

- Player information (ID, Name, LongName, photoUrl, playerUrl, Nationality, Age)
- Performance attributes (OVA, POT, Club, Contract, Positions, Height, Weight, Preferred Foot)
- Skills and abilities (Attacking, Crossing, Finishing, Heading Accuracy, etc.)
- Goalkeeping attributes (GK Diving, GK Handling, GK Kicking, GK Positioning, GK Reflexes)
- Physical attributes (Acceleration, Sprint Speed, Agility, Reactions, Balance, Power)
- Mental attributes (Mentality, Aggression, Interceptions, Positioning, Vision, Penalties)
- Defensive attributes (Defending, Marking, Standing Tackle, Sliding Tackle)
- Total Stats, Base Stats, and other miscellaneous attributes (W/F, SM, A/W, D/W, IR, PAC, SHO, PAS, DRI, DEF, PHY, Hits)


**Goals of Data Cleaning Phase:**

- Handle missing values
- Remove duplicates and redundant data
- Correct errors and inconsistencies
- Transform data into a suitable format for analysis
- Ensure data quality and integrity

By achieving these goals, we will produce a refined and reliable dataset ready for analysis, visualization, and modeling tasks.

## **Import the necessay libraries**

In [2]:
import pandas as pd
import numpy as np
import re # for regex expression
import datetime as dt

## **Import Dataset**

In [4]:
df = pd.read_csv("fifa21 raw data v2.csv")

# first 5 rows
df.head()

<ipython-input-4-65aa585334af>:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("fifa21 raw data v2.csv")

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [5]:
# last 5 rows
df.tail()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [6]:
# Dimension of the dataset
df.shape

(18979, 77)

In [7]:
# Information of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  object
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  object
dtypes: int64(54), object(23)
memory usage: 11.1+ MB

The dataset's information reveals a mix of data types, comprising both object and integer values, and also indicates the presence of null and non-null features, providing a comprehensive overview of the data's structure and content.

In [8]:
# Summary Statistics of the dataset
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,18979.0,226403.384794,27141.054157,41.0,210135.0,232418.0,246922.5,259216.0
Age,18979.0,25.194109,4.710520,16.0,21.0,25.0,29.0,53.0
↓OVA,18979.0,65.718636,6.968999,47.0,61.0,66.0,70.0,93.0
POT,18979.0,71.136414,6.114635,47.0,67.0,71.0,75.0,95.0
BOV,18979.0,66.751726,6.747193,48.0,62.0,67.0,71.0,93.0
Attacking,18979.0,248.938142,74.299428,42.0,222.0,263.0,297.0,437.0
Crossing,18979.0,49.688392,18.131153,6.0,38.0,54.0,63.0,94.0
Finishing,18979.0,45.842405,19.567081,3.0,30.0,49.0,62.0,95.0
Heading Accuracy,18979.0,51.942726,17.294409,5.0,44.0,55.0,64.0,93.0
Short Passing,18979.0,58.768112,14.519106,7.0,54.0,62.0,68.0,94.0
Volleys,18979.0,42.696507,17.646937,3.0,30.0,44.0,56.0,90.0
Skill,18979.0,256.479214,78.650601,40.0,222.0,269.0,310.0,470.0
Dribbling,18979.0,55.587491,18.761314,5.0,49.0,61.0,68.0,96.0
Curve,18979.0,47.246957,18.207790,4.0,35.0,49.0,61.0,94.0
FK Accuracy,18979.0,42.391011,17.227947,5.0,31.0,41.0,55.0,94.0
Long Passing,18979.0,52.725381,15.178151,5.0,43.0,56.0,64.0,93.0
Ball Control,18979.0,58.528373,16.565892,5.0,54.0,63.0,69.0,96.0
Movement,18979.0,317.718689,55.879046,122.0,289.0,327.0,356.0,464.0
Acceleration,18979.0,64.357553,14.889981,13.0,57.0,67.0,74.0,97.0
Sprint Speed,18979.0,64.412930,14.638743,12.0,57.0,67.0,74.0,96.0
Agility,18979.0,63.366721,14.596277,14.0,55.0,66.0,74.0,96.0
Reactions,18979.0,61.655619,9.072114,24.0,56.0,62.0,68.0,95.0
Balance,18979.0,63.925865,14.062285,12.0,56.0,66.0,74.0,97.0
Power,18979.0,296.605195,50.732390,122.0,264.0,302.0,334.0,444.0
Shot Power,18979.0,57.801676,13.308747,18.0,48.0,59.0,68.0,95.0
Jumping,18979.0,64.577375,11.844870,15.0,58.0,65.0,73.0,95.0
Stamina,18979.0,62.653986,15.804223,12.0,55.0,66.0,73.0,97.0
Strength,18979.0,64.786922,12.488672,16.0,57.0,66.0,74.0,97.0
Long Shots,18979.0,46.785236,19.300534,4.0,32.0,51.0,62.0,94.0
Mentality,18979.0,254.199747,64.595613,50.0,227.5,263.0,297.0,421.0
Aggression,18979.0,55.591285,17.140414,9.0,44.0,58.0,69.0,96.0
Interceptions,18979.0,46.394489,20.698078,3.0,25.0,53.0,64.0,91.0
Positioning,18979.0,50.298962,19.428701,2.0,40.0,55.0,64.0,95.0
Vision,18979.0,53.857105,13.708574,9.0,45.0,55.0,64.0,95.0
Penalties,18979.0,48.057906,15.655999,6.0,39.0,49.0,60.0,92.0
Composure,18979.0,58.073660,12.079110,12.0,50.0,59.0,67.0,96.0
Defending,18979.0,139.909268,61.219472,20.0,83.0,159.0,191.0,272.0
Marking,18979.0,46.559197,20.139324,3.0,29.0,52.0,63.0,94.0
Standing Tackle,18979.0,47.705622,21.367690,5.0,27.0,55.0,65.0,93.0
Sliding Tackle,18979.0,45.644449,20.922087,4.0,25.0,52.0,63.0,90.0
Goalkeeping,18979.0,81.436693,84.665579,10.0,48.0,53.0,59.0,440.0
GK Diving,18979.0,16.416302,17.554194,2.0,8.0,11.0,14.0,90.0
GK Handling,18979.0,16.207124,16.816305,2.0,8.0,11.0,14.0,92.0
GK Kicking,18979.0,16.076453,16.491103,2.0,8.0,11.0,14.0,93.0
GK Positioning,18979.0,16.217187,17.002239,2.0,8.0,11.0,14.0,91.0
GK Reflexes,18979.0,16.519627,17.854079,2.0,8.0,11.0,14.0,90.0
Total Stats,18979.0,1595.286949,269.874789,747.0,1452.0,1627.0,1781.0,2316.0
Base Stats,18979.0,355.702197,40.761117,232.0,327.0,356.0,384.0,498.0
PAC,18979.0,67.453975,10.677859,25.0,61.0,68.0,75.0,96.0
SHO,18979.0,53.457031,13.827425,16.0,44.0,56.0,64.0,93.0
PAS,18979.0,57.681016,10.081857,25.0,51.0,58.0,64.0,93.0
DRI,18979.0,62.875020,9.927415,25.0,57.0,64.0,69.0,95.0
DEF,18979.0,49.866221,16.443213,12.0,35.0,53.0,63.0,91.0
PHY,18979.0,64.368934,9.601883,28.0,58.0,65.0,71.0,91.0

The summary statistics above displays the count, mean, standard deviation, minimum, percentile and maximum values of all numeric data.

In [9]:
# Check the column names
df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [10]:
# Drop Unnecessary redundant columns
df.drop(columns = ["Name", "photoUrl", "playerUrl"], inplace = True)

We removed the columns because they lacked relevant information and/or are redundant in the dataset.

In [11]:
# Renaming the columns to improve readability and understanding of the data
df = df.rename(columns= {"LongName":"Name","↓OVA":"Overall_Rating",
                "POT": "Potential_Rating", "W/F": "Weak_Foot",
               "SM": "Skill_Moves", "A/W":"Attack_Willingness", "FK Accuracy" : "Free_Kick_Accuracy",
                "GK Diving" :"Goal_Keeper_Diving",
               "PAC": "Passing", "DRI":"Dribbling", "DEF": "Defending",
               "PHY": "Physicality", "BOV": "Ball_Outreach_Vision"})

## **Handling Missing Values**

In [12]:
# Number of missing values
df.isnull().sum().to_dict()

# Alternatively, df.isnull().to_frame().transpose()

{'ID': 0,
 'Name': 0,
 'Nationality': 0,
 'Age': 0,
 'Overall_Rating': 0,
 'Potential_Rating': 0,
 'Club': 0,
 'Contract': 0,
 'Positions': 0,
 'Height': 0,
 'Weight': 0,
 'Preferred Foot': 0,
 'Ball_Outreach_Vision': 0,
 'Best Position': 0,
 'Joined': 0,
 'Loan Date End': 17966,
 'Value': 0,
 'Wage': 0,
 'Release Clause': 0,
 'Attacking': 0,
 'Crossing': 0,
 'Finishing': 0,
 'Heading Accuracy': 0,
 'Short Passing': 0,
 'Volleys': 0,
 'Skill': 0,
 'Dribbling': 0,
 'Curve': 0,
 'Free_Kick_Accuracy': 0,
 'Long Passing': 0,
 'Ball Control': 0,
 'Movement': 0,
 'Acceleration': 0,
 'Sprint Speed': 0,
 'Agility': 0,
 'Reactions': 0,
 'Balance': 0,
 'Power': 0,
 'Shot Power': 0,
 'Jumping': 0,
 'Stamina': 0,
 'Strength': 0,
 'Long Shots': 0,
 'Mentality': 0,
 'Aggression': 0,
 'Interceptions': 0,
 'Positioning': 0,
 'Vision': 0,
 'Penalties': 0,
 'Composure': 0,
 'Defending': 0,
 'Marking': 0,
 'Standing Tackle': 0,
 'Sliding Tackle': 0,
 'Goalkeeping': 0,
 'Goal_Keeper_Diving': 0,
 'GK Handling': 0,
 'GK Kicking': 0,
 'GK Positioning': 0,
 'GK Reflexes': 0,
 'Total Stats': 0,
 'Base Stats': 0,
 'Weak_Foot': 0,
 'Skill_Moves': 0,
 'Attack_Willingness': 0,
 'D/W': 0,
 'IR': 0,
 'Passing': 0,
 'SHO': 0,
 'PAS': 0,
 'Physicality': 0,
 'Hits': 2595}

With the exception of "Loan Date End" and "Hits", which have 17,966 and 2,595 missing values respectively, all features have complete data. To address this, we can either drop these columns or replace the missing values with suitable alternatives such as mean, mode, median, or other relevant values. For the purpose of data cleaning, we will opt to replace the missing values to maintain data integrity and facilitate analysis.

### Handling Missing Data in the Loan Date End Feature

In [13]:
# Count the missing and non missing values
df["Loan Date End"].isna().value_counts()

Loan Date End
True     17966
False     1013
Name: count, dtype: int64

In [14]:
# Unique values
df["Loan Date End"].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

We are to conduct a cross-validation exercise to verify the missing values in the "Loan Date End" feature by cross-checking them against the "Contract" and "Joined" features, seeking any potential correlations or matches, and printing the results to ensure data accuracy and consistency.

In [15]:
# filter out the nan rows in loan date end column
filtered_null_loan = df[df["Loan Date End"].isna()]

# Print
print(f"\n The null values:")
print(filtered_null_loan[["Loan Date End","Contract","Joined" ]].sample(10))

 The null values:
      Loan Date End     Contract        Joined
16399           NaN  2020 ~ 2020  Jul 31, 2020
18584           NaN  2020 ~ 2024   Jan 1, 2020
6542            NaN  2019 ~ 2023   Jan 1, 2019
14627           NaN  2019 ~ 2022   Mar 9, 2019
18865           NaN  2019 ~ 2024   Jan 1, 2019
10473           NaN  2020 ~ 2020   Jan 7, 2020
4030            NaN         Free   Feb 6, 2020
13808           NaN  2020 ~ 2023  Jul 15, 2020
15541           NaN  2017 ~ 2021  Jan 31, 2017
14971           NaN  2019 ~ 2024  Jun 24, 2019

In [19]:
# crosscheck the contract and loan date end columns for correspondance
filtered_not_null =df[df["Loan Date End"].notna()]

# print result
print(f"\n The not-null values:""\n")
print(filtered_not_null[["Loan Date End", "Contract", "Joined"]].sample(20))

 The not-null values:

      Loan Date End              Contract        Joined
14837  Jun 30, 2022  Jun 30, 2022 On Loan   Jul 1, 2019
1281   Jun 30, 2021  Jun 30, 2021 On Loan  Aug 22, 2015
14759  Jun 30, 2021  Jun 30, 2021 On Loan   Aug 1, 2019
7275   Jun 30, 2021  Jun 30, 2021 On Loan   Jul 1, 2019
13108  Jun 30, 2021  Jun 30, 2021 On Loan   Jul 5, 2019
17770  Nov 30, 2020  Nov 30, 2020 On Loan  Mar 12, 2018
446    Jun 30, 2021  Jun 30, 2021 On Loan  Jun 11, 2018
770    Jun 30, 2021  Jun 30, 2021 On Loan  Aug 31, 2017
7284   Dec 31, 2020  Dec 31, 2020 On Loan   Aug 7, 2018
7225   Jun 30, 2021  Jun 30, 2021 On Loan  Jan 25, 2019
3379   Jun 30, 2021  Jun 30, 2021 On Loan   Jul 1, 2016
13910  Jun 30, 2021  Jun 30, 2021 On Loan   Jul 2, 2018
3086   Jun 30, 2021  Jun 30, 2021 On Loan  Jul 16, 2018
13102  Jun 30, 2021  Jun 30, 2021 On Loan  Aug 27, 2018
13089  Jun 30, 2021  Jun 30, 2021 On Loan  Jun 24, 2016
6768   Jun 30, 2021  Jun 30, 2021 On Loan   Aug 9, 2018
4276   Dec 31, 2020  Dec 31, 2020 On Loan  Aug 31, 2017
1707   Jun 30, 2021  Jun 30, 2021 On Loan   Aug 8, 2019
15138  Jun 30, 2021  Jun 30, 2021 On Loan  Aug 31, 2019
16290  Jun 30, 2021  Jun 30, 2021 On Loan   Jul 1, 2019

Upon observing that the 'Contract' feature dates align with the 'Loan Date End' feature, we can conclude that the missing 'Loan Date End' values can be reliably replaced with the corresponding 'Contract' values, ensuring data consistency and accuracy. However, since the dates are identical and the 'Contract' feature also indicates loan status, we opt to drop the redundant 'Loan Date End' feature, preserving data efficiency and clarity.

In [20]:
# drop Loan Date End column
df = df.drop(columns=["Loan Date End"])

### Imputing Missing Values in the Hits Feature

In [21]:
# Count the missing and non missing values
df["Hits"].isna().value_counts()

Hits
False    16384
True      2595
Name: count, dtype: int64

In [22]:
# Unique Values
df["Hits"].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', nan, 11.0,
       2.0, 1.0, 31.0, 3.0, 10.0, 9.0, 17.0, 7.0, 4.0, 6.0], dtype=object)

The null values in the "Hits" feature will be replaced with zero, signifying no tackles or contact, thereby acknowledging potential non-participation in plays or lack of recorded tackles, and providing a more comprehensive understanding of player performance by accounting for these instances.

In [39]:
# Replace with Zero
df["Hits"] = df["Hits"].fillna(0)

# Checking if the changes had the desired impact
df["Hits"].isna().sum()

0

With the successful replacement of null values in the "Hits" and "Loan Date End" features, we have effectively addressed the issue of missing data, ensuring a more complete and accurate dataset.

## **Checking Duplicates**

In [24]:
# Check for duplicates
df.duplicated().any()

False

Since there are no duplicates, we move on to the next cleaning phase.

## **Standardizing Data Format**

"Next, we will standardize the data by transforming columns into a consistent and uniform format, making it more efficient to work with and analyze.
These features include:

*  Height and Weight
*  Hits
*  Club
*  Value, Wage, Release Clause
*  IR
*  Name
* Contract

### A) Convert Height and Weight To Numerical data

#### Height Feature:

In [26]:
# Info of the features
df[["Height", "Weight"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  18979 non-null  object
 1   Weight  18979 non-null  object
dtypes: object(2)
memory usage: 296.7+ KB

In [27]:
# Display unique values within feature
df["Height"].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

The "Height" feature, currently stored as an object data type, exhibits inconsistent formatting, with values expressed in both centimeters (cm) and feet & inches. To achieve numerical uniformity, we must first remove the unit labels (cm) and then convert the feet and inches values to centimeters, enabling a successful conversion to a numerical data type.

In [28]:
# Replace cm with " "
df["Height"] =  df["Height"].str.replace("cm", "")

In [29]:
# function to convert height in feet and inches to cm
def convert_to_cm(x):
  """
  Converts a height measurement to centimeters.

  Parameters:
  x (str or float): The height measurement to convert.

  Returns:
  float: The height measurement in centimeters .
  """
  if '\'' in x:
        feet, inches = x.split('\'')
        inches = inches.replace('"', '')
        total_inches = int(feet) * 12 + int(inches)
        cm = total_inches * 2.54
        return cm
  else:
        return float(x)

# Apply the function to the Height column
df['Height'] = df['Height'].apply(convert_to_cm)

# Convert the Height column to integer
df['Height'] = df['Height'].astype(int)

In [30]:
# Verifying the effectiveness of the changes
df['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 162,
       201, 158, 161, 160, 203, 157, 156, 202, 159, 206, 155])

#### Weight Feature:

In [31]:
df["Weight"].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

The "Weight" feature contains values expressed in both kilograms (kg) and pounds (lbs), necessitating a conversion to a standardized unit. Specifically, we need to convert the pounds values to kilograms, extract the numerical values by removing the unit labels, and finally convert the column to a numerical data type.

In [32]:
# Function to convert Ibs to kg
def convert_to_kg(column, kg = 0.453592):
   """
   Converts a weight value from pounds (lbs) to kilograms (kg).

   Parameters:
   column (str or numeric): The weight value to convert. Can be a string containing "lbs" or a numeric value.
   kg (float, optional): The conversion factor from pounds to kilograms. Default is 0.453592.

   Returns:
   float: The converted weight value in kilograms.

   Notes:
   If the input is a string that doesn't contain "lbs", it is returned unchanged.
   """
   if isinstance(column, str):
        if "lbs" in column:
            con_kg = float(column.replace("lbs", "")) * kg
            return con_kg
        elif "kg" in column:
            return float(column.replace("kg", ""))
   return column

# Applying the function to the "Weight" column
df["Weight"] = df["Weight"].apply(convert_to_kg)

# Converting to int
df["Weight"] =  df["Weight"].astype(int)

In [33]:
# Verifying the effectiveness of the changes
df["Weight"].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52])

In [34]:
# Modify the columns name to show the unit of measurement at the header
df = df.rename(columns ={"Height": "Height(cm)",
                    "Weight": "Weight(kg)"})

#### Hits Feature:

In [35]:
df["Hits"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 18979 entries, 0 to 18978
Series name: Hits
Non-Null Count  Dtype
--------------  -----
18979 non-null  object
dtypes: object(1)
memory usage: 148.4+ KB

In [36]:
df["Hits"].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', 0, 11.0,
       2.0, 1.0, 31.0, 3.0, 10.0, 9.0, 17.0, 7.0, 4.0, 6.0], dtype=object)

The "Hits" feature, currently represented as an object data type, requires standardization and cleaning. Some values in this column are expressed in thousands, denoted by the abbreviation "k", and also float values. To ensure consistency, we need to remove the "k" notation, multiply the values by 1000, and convert the column to an integer data type. This will enable us to uniformly represent the number of tackles made by a player in a season, allowing for accurate analysis and processing.

In [41]:
def convert_to_thousand(x):
  """
    Converts a string value to a float,
    multiplying by 1000 if the value is in thousands (denoted by "K").

    Parameters:

    - x (string): The value to be converted.

    Returns:

    - thou_hits (float): The converted value.
  """
  if type(x) == str:  # Check if x is a string
        if "K" in x:
            thou_hits = float(x.replace("K"," ")) * 1000
            return thou_hits
  else:
    return float(x)

# Applying the function to the "Hits" column
df["Hits"] = df["Hits"].apply(convert_to_thousand)

In [42]:
# Convert data type to int
df["Hits"] = df["Hits"].astype(int)

# Verifying the effectiveness of the changes
df["Hits"].unique()

array([   0, 1600, 1100, 1500, 3200, 1700, 2300, 1900, 2000, 1300, 3000,
       1400, 2800, 1800, 8400, 4300, 1200, 1000, 2500, 6000,   11,    2,
          1,   31,    3,   10,    9,   17,    7,    4,    6])

#### Club Feature:

In [43]:
# Unique values in Club features
df["Club"].unique()

array(['\n\n\n\nFC Barcelona', '\n\n\n\nJuventus',
       '\n\n\n\nAtlético Madrid', '\n\n\n\nManchester City',
       '\n\n\n\nParis Saint-Germain', '\n\n\n\nFC Bayern München',
       '\n\n\n\nLiverpool', '\n\n\n\nReal Madrid', '\n\n\n\nChelsea',
       '\n\n\n\nTottenham Hotspur', '\n\n\n\nInter', '\n\n\n\nNapoli',
       '\n\n\n\nBorussia Dortmund', '\n\n\n\nManchester United',
       '\n\n\n\nArsenal', '\n\n\n\nLazio', '\n\n\n\nLeicester City',
       '\n\n\n\nBorussia Mönchengladbach', '\n\n\n\nReal Sociedad',
       '\n\n\n\nAtalanta', '\n\n\n\nOlympique Lyonnais', '\n\n\n\nMilan',
       '\n\n\n\nVillarreal CF', '\n\n\n\nRB Leipzig', '\n\n\n\nCagliari',
       '\n\n\n\nAjax', '\n\n\n\nSL Benfica', '\n\n\n\nAS Monaco',
       '\n\n\n\nWolverhampton Wanderers', '\n\n\n\nEverton',
       '\n\n\n\nFiorentina', '\n\n\n\nFC Porto', '\n\n\n\nRC Celta',
       '\n\n\n\nTorino', '\n\n\n\nSevilla FC', '\n\n\n\nGrêmio',
       '\n\n\n\nReal Betis', '\n\n\n\nRoma', '\n\n\n\nNewcastle United',
       '\n\n\n\nEintracht Frankfurt', '\n\n\n\nValencia CF',
       '\n\n\n\nMedipol Başakşehir FK', '\n\n\n\nInter Miami',
       '\n\n\n\nBayer 04 Leverkusen', '\n\n\n\nLevante UD',
       '\n\n\n\nCrystal Palace', '\n\n\n\nAthletic Club de Bilbao',
       '\n\n\n\nShanghai SIPG FC', '\n\n\n\nVfL Wolfsburg',
       '\n\n\n\nGuangzhou Evergrande Taobao FC', '\n\n\n\nAl Shabab',
       '\n\n\n\nOlympique de Marseille', '\n\n\n\nLos Angeles FC',
       '\n\n\n\nBeijing Sinobo Guoan FC', '\n\n\n\nGetafe CF',
       '\n\n\n\nSV Werder Bremen', '\n\n\n\nTSG 1899 Hoffenheim',
       '\n\n\n\nLOSC Lille', '\n\n\n\nDeportivo Alavés',
       '\n\n\n\nBurnley', '\n\n\n\nLeeds United', '\n\n\n\nFulham',
       '\n\n\n\nPFC CSKA Moscow', '\n\n\n\nGenoa',
       '\n\n\n\nGalatasaray SK', '\n\n\n\nAtlanta United',
       '\n\n\n\nAtlético Mineiro', '\n\n\n\nFlamengo',
       '\n\n\n\nPalmeiras', 'No Club', '\n\n\n\nSão Paulo',
       '\n\n\n\nWest Ham United', '\n\n\n\nSD Eibar',
       '\n\n\n\nRiver Plate', '\n\n\n\nOGC Nice',
       '\n\n\n\nReal Valladolid CF', '\n\n\n\nSporting CP', '\n\n\n\nPSV',
       '\n\n\n\nFeyenoord', '\n\n\n\nClub Brugge KV',
       '\n\n\n\nShakhtar Donetsk', '\n\n\n\nVissel Kobe',
       '\n\n\n\nBoca Juniors', '\n\n\n\n1. FC Union Berlin',
       '\n\n\n\nDalian YiFang FC', '\n\n\n\nAS Saint-Étienne',
       '\n\n\n\nSassuolo', '\n\n\n\nTigres U.A.N.L.',
       '\n\n\n\nDinamo Zagreb', '\n\n\n\nDynamo Kyiv',
       '\n\n\n\nFluminense', '\n\n\n\nUdinese', '\n\n\n\nAston Villa',
       '\n\n\n\nStade Rennais FC', '\n\n\n\nBeşiktaş JK',
       '\n\n\n\nBrighton & Hove Albion', '\n\n\n\nHebei China Fortune FC',
       '\n\n\n\nSouthampton', '\n\n\n\nLokomotiv Moscow',
       '\n\n\n\nJiangsu Suning FC', '\n\n\n\nAl Hilal',
       '\n\n\n\nWest Bromwich Albion', '\n\n\n\nFenerbahçe SK',
       '\n\n\n\nFC Groningen', '\n\n\n\nGuangzhou R&F FC',
       '\n\n\n\nOrlando City SC', '\n\n\n\nSampdoria',
       '\n\n\n\nStade de Reims', '\n\n\n\nSheffield United',
       '\n\n\n\nSantos', '\n\n\n\nInternacional', '\n\n\n\nCoritiba',
       '\n\n\n\nCA Osasuna', '\n\n\n\nLA Galaxy', '\n\n\n\nAl Nassr',
       '\n\n\n\nSC Freiburg', '\n\n\n\nSC Braga',
       '\n\n\n\nOlympiacos CFP', '\n\n\n\nToronto FC',
       '\n\n\n\nGranada CF', '\n\n\n\nFC Schalke 04',
       '\n\n\n\nRC Strasbourg Alsace', '\n\n\n\nHertha BSC',
       '\n\n\n\nAZ Alkmaar', '\n\n\n\nSeattle Sounders FC',
       '\n\n\n\nMontpellier HSC', '\n\n\n\nShanghai Greenland Shenhua FC',
       '\n\n\n\nHamburger SV', '\n\n\n\nGirona FC', '\n\n\n\nRacing Club',
       '\n\n\n\nPortland Timbers', '\n\n\n\nFC Girondins de Bordeaux',
       '\n\n\n\nWatford', '\n\n\n\nEstudiantes de La Plata',
       '\n\n\n\nClub América', '\n\n\n\nVitória Guimarães',
       '\n\n\n\nSK Slavia Praha', '\n\n\n\nTrabzonspor',
       '\n\n\n\nRCD Espanyol', '\n\n\n\nFC Nantes', '\n\n\n\nAngers SCO',
       '\n\n\n\nCruz Azul', '\n\n\n\nBSC Young Boys', '\n\n\n\nClub León',
       '\n\n\n\nSpartak Moscow', '\n\n\n\nSivasspor', '\n\n\n\nElche CF',
       '\n\n\n\nFC Augsburg', '\n\n\n\nWuhan Zall', '\n\n\n\nParma',
       '\n\n\n\nRoyal Antwerp FC', '\n\n\n\nMonterrey',
       '\n\n\n\nSan Lorenzo de Almagro', '\n\n\n\nAC Monza',
       '\n\n\n\nClub Atlético Lanús', '\n\n\n\nSD Huesca',
       '\n\n\n\nDerby County', '\n\n\n\nKayserispor',
       '\n\n\n\nRSC Anderlecht', '\n\n\n\nCD Leganés',
       '\n\n\n\nVélez Sarsfield', '\n\n\n\nStade Brestois 29',
       '\n\n\n\nTianjin TEDA FC', '\n\n\n\nBirmingham City',
       '\n\n\n\nHellas Verona', '\n\n\n\n1. FC Köln', '\n\n\n\nAl Wehda',
       '\n\n\n\nBournemouth', '\n\n\n\nAlanyaspor', '\n\n\n\nBologna',
       '\n\n\n\nAmiens SC', '\n\n\n\nCeltic',
       '\n\n\n\nShijiazhuang Ever Bright F.C.', '\n\n\n\nClub Atlas',
       '\n\n\n\nAl Ahli', '\n\n\n\nNorwich City',
       '\n\n\n\nFatih Karagümrük S.K.', '\n\n\n\nClub Tijuana',
       '\n\n\n\nUniversidad Católica', '\n\n\n\nGoiás',
       '\n\n\n\nBenevento', '\n\n\n\nIndependiente',
       '\n\n\n\nQingdao Huanghai F.C.', '\n\n\n\nBrentford',
       '\n\n\n\nAEK Athens', '\n\n\n\nRacing Club de Lens',
       '\n\n\n\nOlimpia Asunción', '\n\n\n\nShenzhen FC',
       '\n\n\n\nÇaykur Rizespor', '\n\n\n\nKAA Gent',
       '\n\n\n\nNew England Revolution', '\n\n\n\nCádiz CF',
       '\n\n\n\n1. FSV Mainz 05', '\n\n\n\nVasco da Gama',
       '\n\n\n\nFC Midtjylland', '\n\n\n\nAl Ain FC',
       '\n\n\n\nSantos Laguna', '\n\n\n\nSPAL', '\n\n\n\nPerth Glory',
       '\n\n\n\nFC Utrecht', '\n\n\n\nMontreal Impact',
       '\n\n\n\nUD Almería', '\n\n\n\nFortaleza', '\n\n\n\nSpezia',
       '\n\n\n\nFC Basel 1893', '\n\n\n\nFC København',
       '\n\n\n\nGodoy Cruz', '\n\n\n\nDeportivo Toluca',
       '\n\n\n\nNacional de Montevideo', '\n\n\n\nAalborg BK',
       '\n\n\n\nRio Ave FC', '\n\n\n\nFC Metz',
       '\n\n\n\nChongqing Dangdai Lifan FC SWM Team',
       '\n\n\n\nRosenborg BK', '\n\n\n\nFC Red Bull Salzburg',
       '\n\n\n\nBotafogo', '\n\n\n\nDSC Arminia Bielefeld',
       '\n\n\n\nClub Athletico Paranaense', '\n\n\n\nRCD Mallorca',
       '\n\n\n\nPachuca', '\n\n\n\nSwansea City', '\n\n\n\nKRC Genk',
       '\n\n\n\nEn Avant de Guingamp', '\n\n\n\nLecce',
       '\n\n\n\nNîmes Olympique', '\n\n\n\nColo-Colo',
       '\n\n\n\nStade Malherbe Caen', '\n\n\n\nColumbus Crew SC',
       '\n\n\n\nJunior FC', '\n\n\n\nVfB Stuttgart',
       '\n\n\n\nMoreirense FC', '\n\n\n\nRangers FC', '\n\n\n\nMalmö FF',
       '\n\n\n\nShandong Luneng TaiShan FC', '\n\n\n\nSparta Praha',
       '\n\n\n\nHatayspor', '\n\n\n\nChicago Fire',
       '\n\n\n\nToulouse Football Club', '\n\n\n\nFC Seoul',
       '\n\n\n\nAntalyaspor', '\n\n\n\nDeportivo Cali',
       '\n\n\n\nKaizer Chiefs', '\n\n\n\nReal Zaragoza',
       '\n\n\n\nAtlético Clube Goianiense', '\n\n\n\nPuebla FC',
       '\n\n\n\nFortuna Düsseldorf', '\n\n\n\nWestern United FC',
       '\n\n\n\nAstra Giurgiu', '\n\n\n\nHenan Jianye FC',
       '\n\n\n\nBahia', '\n\n\n\nFamalicão', '\n\n\n\nAtiker Konyaspor',
       '\n\n\n\nPeñarol', '\n\n\n\nDC United', '\n\n\n\nNew York City FC',
       '\n\n\n\nArgentinos Juniors', '\n\n\n\nU.N.A.M.',
       '\n\n\n\nMinnesota United FC', '\n\n\n\nNottingham Forest',
       '\n\n\n\nIndependiente del Valle', '\n\n\n\nDefensa y Justicia',
       '\n\n\n\nPhiladelphia Union', "\n\n\n\nNewell's Old Boys",
       '\n\n\n\nRosario Central', '\n\n\n\nAtlético de San Luis',
       '\n\n\n\nFC Dallas', '\n\n\n\nDenizlispor',
       '\n\n\n\nYeni Malatyaspor', '\n\n\n\nClub Atlético Colón',
       '\n\n\n\nHouston Dynamo', '\n\n\n\nMillwall',
       '\n\n\n\nClube Sport Marítimo', '\n\n\n\nMKE Ankaragücü',
       '\n\n\n\nGuadalajara', '\n\n\n\nBoavista FC',
       '\n\n\n\nSporting Kansas City', '\n\n\n\nAtlético Nacional',
       '\n\n\n\nCD Lugo', '\n\n\n\nNew York Red Bulls', '\n\n\n\nPAOK',
       '\n\n\n\nSC Heerenveen', '\n\n\n\nDaegu FC',
       '\n\n\n\nPreston North End', '\n\n\n\nDamac FC', '\n\n\n\nBrescia',
       '\n\n\n\nVfL Bochum 1848', '\n\n\n\nVancouver Whitecaps FC',
       '\n\n\n\nSV Sandhausen', '\n\n\n\nRoyal Excel Mouscron',
       '\n\n\n\nDijon FCO', '\n\n\n\nMolde FK',
       '\n\n\n\nPanathinaikos FC', '\n\n\n\nLASK Linz',
       '\n\n\n\nUlsan Hyundai FC', '\n\n\n\nReal Salt Lake',
       '\n\n\n\nFC Luzern', '\n\n\n\nViktoria Plzeň',
       '\n\n\n\nOrlando Pirates', '\n\n\n\nAl Ittihad',
       '\n\n\n\n1. FC Nürnberg', '\n\n\n\nStandard de Liège',
       '\n\n\n\nRayo Vallecano', '\n\n\n\nClub Libertad',
       '\n\n\n\nJeonbuk Hyundai Motors',
       '\n\n\n\nWestern Sydney Wanderers', '\n\n\n\nUnión de Santa Fe',
       '\n\n\n\nFC Sion', '\n\n\n\nSydney FC', '\n\n\n\nHannover 96',
       '\n\n\n\nReal Sporting de Gijón', '\n\n\n\nFC Cincinnati',
       '\n\n\n\nESTAC Troyes', '\n\n\n\nSan Jose Earthquakes',
       '\n\n\n\nClub Guaraní', '\n\n\n\nFC Lorient',
       '\n\n\n\nGençlerbirliği SK', '\n\n\n\nSporting de Charleroi',
       '\n\n\n\nWisła Kraków', '\n\n\n\nAl Taawoun', '\n\n\n\nReading',
       '\n\n\n\nGazişehir Gaziantep F.K.', '\n\n\n\nBlackburn Rovers',
       '\n\n\n\nKashiwa Reysol', '\n\n\n\nFK Bodø/Glimt',
       '\n\n\n\nWillem II', '\n\n\n\nVitesse', '\n\n\n\nGil Vicente FC',
       '\n\n\n\nSønderjyskE', '\n\n\n\nYokohama F. Marinos',
       '\n\n\n\nFC St. Gallen', '\n\n\n\nClub Atlético Aldosivi',
       '\n\n\n\nGöztepe SK', '\n\n\n\nHolstein Kiel', '\n\n\n\nFC Juárez',
       '\n\n\n\nFCSB (Steaua)', '\n\n\n\nEttifaq FC', '\n\n\n\nKAS Eupen',
       '\n\n\n\nFC Tokyo', '\n\n\n\nMelbourne City FC',
       '\n\n\n\nUniversitatea Craiova', '\n\n\n\nCD Tondela',
       '\n\n\n\nWolfsberger AC', '\n\n\n\nCeará Sporting Club',
       '\n\n\n\nRiver Plate Asunción', '\n\n\n\nStoke City',
       '\n\n\n\nParis FC', '\n\n\n\nIFK Norrköping', '\n\n\n\nCrotone',
       '\n\n\n\nCardiff City', '\n\n\n\nAmérica de Cali',
       '\n\n\n\nAl Faisaly', '\n\n\n\nIndependiente Medellín',
       '\n\n\n\nPortimonense SC', '\n\n\n\nCD Tenerife',
       '\n\n\n\nHeracles Almelo', '\n\n\n\nNashville SC',
       '\n\n\n\nSK Rapid Wien', '\n\n\n\nKawasaki Frontale',
       '\n\n\n\nClub Necaxa', '\n\n\n\nChievo Verona',
       '\n\n\n\nLech Poznań', '\n\n\n\nAIK', '\n\n\n\nFK Austria Wien',
       '\n\n\n\nQuerétaro', '\n\n\n\n1. FC Heidenheim 1846',
       '\n\n\n\nLegia Warszawa', '\n\n\n\nClub Atlético Banfield',
       '\n\n\n\nOs Belenenses', '\n\n\n\nHuddersfield Town',
       '\n\n\n\nKSV Cercle Brugge', '\n\n\n\nLDU Quito',
       '\n\n\n\nGimnasia y Esgrima La Plata', '\n\n\n\nGamba Osaka',
       '\n\n\n\nMiddlesbrough', '\n\n\n\nServette FC', '\n\n\n\nEmpoli',
       '\n\n\n\nReal Oviedo', '\n\n\n\nKasimpaşa SK', '\n\n\n\nCFR Cluj',
       '\n\n\n\nMillonarios FC', '\n\n\n\nFC Paços de Ferreira',
       '\n\n\n\nSint-Truidense VV', '\n\n\n\nAD Alcorcón',
       '\n\n\n\nColorado Rapids', '\n\n\n\nDinamo Bucureşti',
       '\n\n\n\nCerezo Osaka', '\n\n\n\nFC Emmen',
       '\n\n\n\nSheffield Wednesday', '\n\n\n\nFC Erzgebirge Aue',
       '\n\n\n\nRaków Częstochowa', '\n\n\n\nAtlético Tucumán',
       '\n\n\n\nSV Darmstadt 98', '\n\n\n\nBristol City',
       '\n\n\n\nOud-Heverlee Leuven', '\n\n\n\nBarnsley',
       '\n\n\n\nQueens Park Rangers', '\n\n\n\nSangju Sangmu FC',
       '\n\n\n\nHelsingborgs IF', '\n\n\n\nAC Ajaccio',
       '\n\n\n\nOceânico FC', '\n\n\n\nClub Atlético Talleres',
       '\n\n\n\nAl Hazem', '\n\n\n\nSC Paderborn 07',
       '\n\n\n\nClub Atlético Huracán', '\n\n\n\nKV Kortrijk',
       '\n\n\n\nEl Nacional', '\n\n\n\nMazatlán FC', '\n\n\n\nAberdeen',
       '\n\n\n\nCD Mirandés', '\n\n\n\nSV Zulte-Waregem',
       '\n\n\n\nPiast Gliwice', '\n\n\n\nDjurgårdens IF',
       '\n\n\n\nCentral Córdoba', '\n\n\n\nWellington Phoenix',
       '\n\n\n\nDeportivo Binacional', '\n\n\n\nPatronato',
       '\n\n\n\nSpVgg Greuther Fürth', '\n\n\n\nIFK Göteborg',
       '\n\n\n\nFC Cartagena', '\n\n\n\nSanta Clara', '\n\n\n\nFC Twente',
       '\n\n\n\nFarense', '\n\n\n\nADO Den Haag', '\n\n\n\nAJ Auxerre',
       '\n\n\n\nAl Fateh', '\n\n\n\nValenciennes FC',
       '\n\n\n\nHokkaido Consadole Sapporo', '\n\n\n\nFC St. Pauli',
       '\n\n\n\nAlbacete BP', '\n\n\n\n1. FC Kaiserslautern',
       '\n\n\n\nAl Fayha', '\n\n\n\nIncheon United FC',
       '\n\n\n\nKV Mechelen', '\n\n\n\nPohang Steelers',
       '\n\n\n\nCD Nacional', '\n\n\n\nUnión La Calera',
       '\n\n\n\nBB Erzurumspor', '\n\n\n\nKashima Antlers',
       '\n\n\n\nArsenal de Sarandí', '\n\n\n\nHJK Helsinki',
       '\n\n\n\nKarlsruher SC', '\n\n\n\nAarhus GF', '\n\n\n\nFC Zürich',
       '\n\n\n\nBarcelona Sporting Club', '\n\n\n\nSG Dynamo Dresden',
       '\n\n\n\nSanfrecce Hiroshima', '\n\n\n\nAl Raed',
       '\n\n\n\nSD Ponferradina', '\n\n\n\nBrøndby IF',
       '\n\n\n\nLechia Gdańsk', '\n\n\n\nFC Viitorul',
       '\n\n\n\nSK Sturm Graz', '\n\n\n\nIF Elfsborg',
       '\n\n\n\nGangwon FC', '\n\n\n\nMelgar FBC',
       '\n\n\n\nClub Atlético Grau', '\n\n\n\nJagiellonia Białystok',
       '\n\n\n\nWaasland-Beveren', '\n\n\n\nVfL Osnabrück',
       '\n\n\n\nNagoya Grampus', '\n\n\n\nCF Fuenlabrada',
       '\n\n\n\nShamrock Rovers', '\n\n\n\nShimizu S-Pulse',
       '\n\n\n\nRKC Waalwijk', '\n\n\n\nVålerenga Fotball',
       '\n\n\n\nClermont Foot 63', '\n\n\n\nFC Ingolstadt 04',
       '\n\n\n\nFC Würzburger Kickers', '\n\n\n\nGórnik Zabrze',
       '\n\n\n\nCharlton Athletic', '\n\n\n\nBeerschot AC',
       '\n\n\n\nCoquimbo Unido', '\n\n\n\nViktoria Köln',
       '\n\n\n\nHull City', '\n\n\n\nMálaga CF',
       '\n\n\n\nFC Nordsjælland', '\n\n\n\nUD Las Palmas',
       '\n\n\n\nVVV-Venlo', '\n\n\n\nGwangJu FC',
       '\n\n\n\nChamois Niortais Football Club', '\n\n\n\nFC Lugano',
       '\n\n\n\nCusco FC', '\n\n\n\nSparta Rotterdam',
       '\n\n\n\nSol de América', '\n\n\n\nPEC Zwolle',
       '\n\n\n\nPogoń Szczecin', '\n\n\n\nDoncaster Rovers',
       '\n\n\n\nKristiansund BK', '\n\n\n\nLiverpool Fútbol Club',
       '\n\n\n\nClub Bolívar', '\n\n\n\nUrawa Red Diamonds',
       '\n\n\n\nSK Brann', '\n\n\n\nEintracht Braunschweig',
       '\n\n\n\nNacional Asunción', '\n\n\n\nMelbourne Victory',
       '\n\n\n\nKilmarnock', '\n\n\n\nDundalk',
       '\n\n\n\nSSV Jahn Regensburg', '\n\n\n\nAbha Club',
       '\n\n\n\nClub Atlético Tigre', '\n\n\n\nSuwon Samsung Bluewings',
       '\n\n\n\nShonan Bellmare', '\n\n\n\nSD Aucas', '\n\n\n\nEmelec',
       '\n\n\n\nFortuna Sittard', '\n\n\n\nLa Berrichonne de Châteauroux',
       '\n\n\n\nŚląsk Wrocław', '\n\n\n\nCoventry City',
       '\n\n\n\nSunderland', '\n\n\n\nAlianza Lima',
       '\n\n\n\nHammarby IF', '\n\n\n\nCracovia',
       '\n\n\n\nCE Sabadell FC', '\n\n\n\nOita Trinita',
       '\n\n\n\nBK Häcken', '\n\n\n\nLuton Town', '\n\n\n\nLe Havre AC',
       '\n\n\n\nIK Sirius', '\n\n\n\nZagłębie Lubin',
       '\n\n\n\nGrenoble Foot 38', '\n\n\n\nMacarthur FC',
       '\n\n\n\nRodez Aveyron Football', '\n\n\n\nVegalta Sendai',
       '\n\n\n\nMotherwell', '\n\n\n\nSV Wehen Wiesbaden',
       '\n\n\n\nAudax Italiano', '\n\n\n\nGaz Metan Mediaş',
       '\n\n\n\nPortsmouth', '\n\n\n\nHibernian', '\n\n\n\nAlways Ready',
       '\n\n\n\nUD Logroñés', '\n\n\n\nFC Voluntari',
       '\n\n\n\nFC Hermannstadt', '\n\n\n\nAS Nancy Lorraine',
       '\n\n\n\nRotherham United', '\n\n\n\nFleetwood Town',
       '\n\n\n\nJorge Wilstermann', '\n\n\n\nOdense Boldklub',
       '\n\n\n\nMSV Duisburg', '\n\n\n\nFC Sochaux-Montbéliard',
       '\n\n\n\nMilton Keynes Dons', '\n\n\n\nRiver Plate Montevideo',
       '\n\n\n\nDelfín SC', '\n\n\n\nUniversidad Católica del Ecuador',
       '\n\n\n\nDeportivo Pasto', '\n\n\n\nKV Oostende',
       '\n\n\n\nClub Plaza Colonia', '\n\n\n\nWigan Athletic',
       '\n\n\n\nFC Botoşani', '\n\n\n\nC.D. Castellón',
       '\n\n\n\nSCR Altach', '\n\n\n\nÖrebro SK', '\n\n\n\nTSV Hartberg',
       '\n\n\n\nStabæk Fotball', '\n\n\n\nWycombe Wanderers',
       '\n\n\n\nSt. Johnstone FC', '\n\n\n\nOxford United',
       '\n\n\n\nLincoln City', '\n\n\n\nRanders FC', '\n\n\n\nViking FK',
       '\n\n\n\nFC Chambly Oise', '\n\n\n\nDundee United',
       '\n\n\n\nOriente Petrolero', '\n\n\n\nOdds BK',
       '\n\n\n\nNacional Potosí', '\n\n\n\nSepsi OSK',
       '\n\n\n\nFC Hansa Rostock', '\n\n\n\nLyngby BK',
       '\n\n\n\nSpVgg Unterhaching', '\n\n\n\nBrisbane Roar',
       '\n\n\n\nSeongnam FC', '\n\n\n\nSV Ried', '\n\n\n\nCD Huachipato',
       '\n\n\n\nWSG Tirol', '\n\n\n\nPodbeskidzie Bielsko-Biała',
       '\n\n\n\nPeterborough United', '\n\n\n\nClub Blooming',
       '\n\n\n\nWisła Płock', '\n\n\n\nBusan IPark',
       '\n\n\n\nFSV Zwickau', '\n\n\n\nMjøndalen IF',
       '\n\n\n\nVejle Boldklub', '\n\n\n\nPau FC',
       '\n\n\n\nFC Lausanne-Sport', '\n\n\n\nEstudiantes de Mérida',
       '\n\n\n\nSagan Tosu', '\n\n\n\nSV Waldhof Mannheim',
       '\n\n\n\nSport Huancayo', '\n\n\n\nHallescher FC',
       '\n\n\n\nKalmar FF', '\n\n\n\nSt. Mirren',
       '\n\n\n\nSKN St. Pölten', '\n\n\n\nSarpsborg 08 FF',
       '\n\n\n\nShrewsbury', '\n\n\n\nTSV 1860 München',
       '\n\n\n\nSV Meppen', '\n\n\n\nIpswich Town', '\n\n\n\nIK Start',
       '\n\n\n\nAdelaide United', '\n\n\n\nStal Mielec',
       '\n\n\n\nCentro Atlético Fénix', '\n\n\n\nNewcastle Jets',
       '\n\n\n\nLivingston FC', '\n\n\n\nAC Mineros de Guayana',
       '\n\n\n\nAFC Wimbledon', '\n\n\n\nBurton Albion',
       '\n\n\n\nAl Adalah', '\n\n\n\nWarta Poznań',
       '\n\n\n\nUSL Dunkerque', '\n\n\n\nBristol Rovers',
       '\n\n\n\nUTA Arad', '\n\n\n\nÖstersunds FK',
       '\n\n\n\nSportivo Luqueño', '\n\n\n\nPolitehnica Iaşi',
       '\n\n\n\nSalford City', '\n\n\n\nCentral Coast Mariners',
       '\n\n\n\nCaracas FC', '\n\n\n\nAC Horsens',
       '\n\n\n\nPlymouth Argyle', '\n\n\n\nAalesunds FK',
       '\n\n\n\nCrewe Alexandra', '\n\n\n\nChindia Târgovişte',
       '\n\n\n\nOldham Athletic', '\n\n\n\nYokohama FC',
       '\n\n\n\nBlackpool', '\n\n\n\nNorthampton Town',
       '\n\n\n\nBayern München II', '\n\n\n\nFK Haugesund',
       '\n\n\n\nKFC Uerdingen 05', '\n\n\n\nForest Green Rovers',
       '\n\n\n\nCheltenham Town', '\n\n\n\nStrømsgodset IF',
       '\n\n\n\nMjällby AIF', '\n\n\n\nExeter City',
       '\n\n\n\nCambridge United', '\n\n\n\nGrimsby Town',
       '\n\n\n\nFC Vaduz', '\n\n\n\nTürkgücü München',
       '\n\n\n\nVfB Lübeck', '\n\n\n\nBolton Wanderers',
       '\n\n\n\nBradford City', '\n\n\n\n1. FC Magdeburg',
       '\n\n\n\nFC Admira Wacker Mödling',
       '\n\n\n\nHamilton Academical FC', '\n\n\n\nAragua FC',
       '\n\n\n\nAccrington Stanley', '\n\n\n\nSwindon Town',
       '\n\n\n\nCarlisle United', '\n\n\n\nFC Argeș', '\n\n\n\nPort Vale',
       '\n\n\n\nAcademica Clinceni', '\n\n\n\nRochdale',
       '\n\n\n\nGillingham', '\n\n\n\nTranmere Rovers',
       '\n\n\n\nSouthend United', '\n\n\n\n1. FC Saarbrücken',
       '\n\n\n\nColchester United', '\n\n\n\nMansfield Town',
       '\n\n\n\nFalkenbergs FF', '\n\n\n\nSC Verl',
       '\n\n\n\nVarbergs BoIS', '\n\n\n\nCrawley Town',
       '\n\n\n\nSandefjord Fotball', '\n\n\n\nNewport County',
       '\n\n\n\nBohemian FC', '\n\n\n\nRoss County FC',
       '\n\n\n\nScunthorpe United', '\n\n\n\nMorecambe',
       '\n\n\n\nWalsall', '\n\n\n\nLeyton Orient', '\n\n\n\nStevenage',
       '\n\n\n\nBarrow', '\n\n\n\nDerry City',
       '\n\n\n\nLlaneros de Guanare', '\n\n\n\nSligo Rovers',
       '\n\n\n\nZamora FC', "\n\n\n\nSt. Patrick's Athletic",
       '\n\n\n\nCork City', '\n\n\n\nShelbourne FC',
       '\n\n\n\nHarrogate Town', '\n\n\n\nWaterford FC',
       '\n\n\n\nFinn Harps'], dtype=object)

In [44]:
# A random club feature infomation
df["Club"].sample(10)

4926                               \n\n\n\nFulham
14271                              \n\n\n\nBarrow
14943                         \n\n\n\nVissel Kobe
13583                       \n\n\n\nHallescher FC
4913                           \n\n\n\nCD Leganés
10440                    \n\n\n\nKFC Uerdingen 05
12674    \n\n\n\nUniversidad Católica del Ecuador
15096                          \n\n\n\nGwangJu FC
19                                \n\n\n\nChelsea
5394                        \n\n\n\nMiddlesbrough
Name: Club, dtype: object

It is apparent that the players are affiliated with various clubs, and the associated column requires cleaning. To achieve this, we need to perform the following tasks:

- Remove newline characters (\n) to consolidate the data into a single line
- Trim trailing spaces to ensure consistent formatting

In [45]:
# Remove the newlines
df["Club"] = df["Club"].str.replace("\n", " ")

# Determining if the changes were successful
print(f'\nThe unique clubs are:\n')
df["Club"].unique()

The unique clubs are:

array(['    FC Barcelona', '    Juventus', '    Atlético Madrid',
       '    Manchester City', '    Paris Saint-Germain',
       '    FC Bayern München', '    Liverpool', '    Real Madrid',
       '    Chelsea', '    Tottenham Hotspur', '    Inter', '    Napoli',
       '    Borussia Dortmund', '    Manchester United', '    Arsenal',
       '    Lazio', '    Leicester City', '    Borussia Mönchengladbach',
       '    Real Sociedad', '    Atalanta', '    Olympique Lyonnais',
       '    Milan', '    Villarreal CF', '    RB Leipzig', '    Cagliari',
       '    Ajax', '    SL Benfica', '    AS Monaco',
       '    Wolverhampton Wanderers', '    Everton', '    Fiorentina',
       '    FC Porto', '    RC Celta', '    Torino', '    Sevilla FC',
       '    Grêmio', '    Real Betis', '    Roma', '    Newcastle United',
       '    Eintracht Frankfurt', '    Valencia CF',
       '    Medipol Başakşehir FK', '    Inter Miami',
       '    Bayer 04 Leverkusen', '    Levante UD', '    Crystal Palace',
       '    Athletic Club de Bilbao', '    Shanghai SIPG FC',
       '    VfL Wolfsburg', '    Guangzhou Evergrande Taobao FC',
       '    Al Shabab', '    Olympique de Marseille',
       '    Los Angeles FC', '    Beijing Sinobo Guoan FC',
       '    Getafe CF', '    SV Werder Bremen', '    TSG 1899 Hoffenheim',
       '    LOSC Lille', '    Deportivo Alavés', '    Burnley',
       '    Leeds United', '    Fulham', '    PFC CSKA Moscow',
       '    Genoa', '    Galatasaray SK', '    Atlanta United',
       '    Atlético Mineiro', '    Flamengo', '    Palmeiras', 'No Club',
       '    São Paulo', '    West Ham United', '    SD Eibar',
       '    River Plate', '    OGC Nice', '    Real Valladolid CF',
       '    Sporting CP', '    PSV', '    Feyenoord',
       '    Club Brugge KV', '    Shakhtar Donetsk', '    Vissel Kobe',
       '    Boca Juniors', '    1. FC Union Berlin',
       '    Dalian YiFang FC', '    AS Saint-Étienne', '    Sassuolo',
       '    Tigres U.A.N.L.', '    Dinamo Zagreb', '    Dynamo Kyiv',
       '    Fluminense', '    Udinese', '    Aston Villa',
       '    Stade Rennais FC', '    Beşiktaş JK',
       '    Brighton & Hove Albion', '    Hebei China Fortune FC',
       '    Southampton', '    Lokomotiv Moscow', '    Jiangsu Suning FC',
       '    Al Hilal', '    West Bromwich Albion', '    Fenerbahçe SK',
       '    FC Groningen', '    Guangzhou R&F FC', '    Orlando City SC',
       '    Sampdoria', '    Stade de Reims', '    Sheffield United',
       '    Santos', '    Internacional', '    Coritiba',
       '    CA Osasuna', '    LA Galaxy', '    Al Nassr',
       '    SC Freiburg', '    SC Braga', '    Olympiacos CFP',
       '    Toronto FC', '    Granada CF', '    FC Schalke 04',
       '    RC Strasbourg Alsace', '    Hertha BSC', '    AZ Alkmaar',
       '    Seattle Sounders FC', '    Montpellier HSC',
       '    Shanghai Greenland Shenhua FC', '    Hamburger SV',
       '    Girona FC', '    Racing Club', '    Portland Timbers',
       '    FC Girondins de Bordeaux', '    Watford',
       '    Estudiantes de La Plata', '    Club América',
       '    Vitória Guimarães', '    SK Slavia Praha', '    Trabzonspor',
       '    RCD Espanyol', '    FC Nantes', '    Angers SCO',
       '    Cruz Azul', '    BSC Young Boys', '    Club León',
       '    Spartak Moscow', '    Sivasspor', '    Elche CF',
       '    FC Augsburg', '    Wuhan Zall', '    Parma',
       '    Royal Antwerp FC', '    Monterrey',
       '    San Lorenzo de Almagro', '    AC Monza',
       '    Club Atlético Lanús', '    SD Huesca', '    Derby County',
       '    Kayserispor', '    RSC Anderlecht', '    CD Leganés',
       '    Vélez Sarsfield', '    Stade Brestois 29',
       '    Tianjin TEDA FC', '    Birmingham City', '    Hellas Verona',
       '    1. FC Köln', '    Al Wehda', '    Bournemouth',
       '    Alanyaspor', '    Bologna', '    Amiens SC', '    Celtic',
       '    Shijiazhuang Ever Bright F.C.', '    Club Atlas',
       '    Al Ahli', '    Norwich City', '    Fatih Karagümrük S.K.',
       '    Club Tijuana', '    Universidad Católica', '    Goiás',
       '    Benevento', '    Independiente', '    Qingdao Huanghai F.C.',
       '    Brentford', '    AEK Athens', '    Racing Club de Lens',
       '    Olimpia Asunción', '    Shenzhen FC', '    Çaykur Rizespor',
       '    KAA Gent', '    New England Revolution', '    Cádiz CF',
       '    1. FSV Mainz 05', '    Vasco da Gama', '    FC Midtjylland',
       '    Al Ain FC', '    Santos Laguna', '    SPAL',
       '    Perth Glory', '    FC Utrecht', '    Montreal Impact',
       '    UD Almería', '    Fortaleza', '    Spezia',
       '    FC Basel 1893', '    FC København', '    Godoy Cruz',
       '    Deportivo Toluca', '    Nacional de Montevideo',
       '    Aalborg BK', '    Rio Ave FC', '    FC Metz',
       '    Chongqing Dangdai Lifan FC SWM Team', '    Rosenborg BK',
       '    FC Red Bull Salzburg', '    Botafogo',
       '    DSC Arminia Bielefeld', '    Club Athletico Paranaense',
       '    RCD Mallorca', '    Pachuca', '    Swansea City',
       '    KRC Genk', '    En Avant de Guingamp', '    Lecce',
       '    Nîmes Olympique', '    Colo-Colo', '    Stade Malherbe Caen',
       '    Columbus Crew SC', '    Junior FC', '    VfB Stuttgart',
       '    Moreirense FC', '    Rangers FC', '    Malmö FF',
       '    Shandong Luneng TaiShan FC', '    Sparta Praha',
       '    Hatayspor', '    Chicago Fire', '    Toulouse Football Club',
       '    FC Seoul', '    Antalyaspor', '    Deportivo Cali',
       '    Kaizer Chiefs', '    Real Zaragoza',
       '    Atlético Clube Goianiense', '    Puebla FC',
       '    Fortuna Düsseldorf', '    Western United FC',
       '    Astra Giurgiu', '    Henan Jianye FC', '    Bahia',
       '    Famalicão', '    Atiker Konyaspor', '    Peñarol',
       '    DC United', '    New York City FC', '    Argentinos Juniors',
       '    U.N.A.M.', '    Minnesota United FC', '    Nottingham Forest',
       '    Independiente del Valle', '    Defensa y Justicia',
       '    Philadelphia Union', "    Newell's Old Boys",
       '    Rosario Central', '    Atlético de San Luis', '    FC Dallas',
       '    Denizlispor', '    Yeni Malatyaspor',
       '    Club Atlético Colón', '    Houston Dynamo', '    Millwall',
       '    Clube Sport Marítimo', '    MKE Ankaragücü',
       '    Guadalajara', '    Boavista FC', '    Sporting Kansas City',
       '    Atlético Nacional', '    CD Lugo', '    New York Red Bulls',
       '    PAOK', '    SC Heerenveen', '    Daegu FC',
       '    Preston North End', '    Damac FC', '    Brescia',
       '    VfL Bochum 1848', '    Vancouver Whitecaps FC',
       '    SV Sandhausen', '    Royal Excel Mouscron', '    Dijon FCO',
       '    Molde FK', '    Panathinaikos FC', '    LASK Linz',
       '    Ulsan Hyundai FC', '    Real Salt Lake', '    FC Luzern',
       '    Viktoria Plzeň', '    Orlando Pirates', '    Al Ittihad',
       '    1. FC Nürnberg', '    Standard de Liège',
       '    Rayo Vallecano', '    Club Libertad',
       '    Jeonbuk Hyundai Motors', '    Western Sydney Wanderers',
       '    Unión de Santa Fe', '    FC Sion', '    Sydney FC',
       '    Hannover 96', '    Real Sporting de Gijón',
       '    FC Cincinnati', '    ESTAC Troyes',
       '    San Jose Earthquakes', '    Club Guaraní', '    FC Lorient',
       '    Gençlerbirliği SK', '    Sporting de Charleroi',
       '    Wisła Kraków', '    Al Taawoun', '    Reading',
       '    Gazişehir Gaziantep F.K.', '    Blackburn Rovers',
       '    Kashiwa Reysol', '    FK Bodø/Glimt', '    Willem II',
       '    Vitesse', '    Gil Vicente FC', '    SønderjyskE',
       '    Yokohama F. Marinos', '    FC St. Gallen',
       '    Club Atlético Aldosivi', '    Göztepe SK',
       '    Holstein Kiel', '    FC Juárez', '    FCSB (Steaua)',
       '    Ettifaq FC', '    KAS Eupen', '    FC Tokyo',
       '    Melbourne City FC', '    Universitatea Craiova',
       '    CD Tondela', '    Wolfsberger AC', '    Ceará Sporting Club',
       '    River Plate Asunción', '    Stoke City', '    Paris FC',
       '    IFK Norrköping', '    Crotone', '    Cardiff City',
       '    América de Cali', '    Al Faisaly',
       '    Independiente Medellín', '    Portimonense SC',
       '    CD Tenerife', '    Heracles Almelo', '    Nashville SC',
       '    SK Rapid Wien', '    Kawasaki Frontale', '    Club Necaxa',
       '    Chievo Verona', '    Lech Poznań', '    AIK',
       '    FK Austria Wien', '    Querétaro',
       '    1. FC Heidenheim 1846', '    Legia Warszawa',
       '    Club Atlético Banfield', '    Os Belenenses',
       '    Huddersfield Town', '    KSV Cercle Brugge', '    LDU Quito',
       '    Gimnasia y Esgrima La Plata', '    Gamba Osaka',
       '    Middlesbrough', '    Servette FC', '    Empoli',
       '    Real Oviedo', '    Kasimpaşa SK', '    CFR Cluj',
       '    Millonarios FC', '    FC Paços de Ferreira',
       '    Sint-Truidense VV', '    AD Alcorcón', '    Colorado Rapids',
       '    Dinamo Bucureşti', '    Cerezo Osaka', '    FC Emmen',
       '    Sheffield Wednesday', '    FC Erzgebirge Aue',
       '    Raków Częstochowa', '    Atlético Tucumán',
       '    SV Darmstadt 98', '    Bristol City',
       '    Oud-Heverlee Leuven', '    Barnsley',
       '    Queens Park Rangers', '    Sangju Sangmu FC',
       '    Helsingborgs IF', '    AC Ajaccio', '    Oceânico FC',
       '    Club Atlético Talleres', '    Al Hazem',
       '    SC Paderborn 07', '    Club Atlético Huracán',
       '    KV Kortrijk', '    El Nacional', '    Mazatlán FC',
       '    Aberdeen', '    CD Mirandés', '    SV Zulte-Waregem',
       '    Piast Gliwice', '    Djurgårdens IF', '    Central Córdoba',
       '    Wellington Phoenix', '    Deportivo Binacional',
       '    Patronato', '    SpVgg Greuther Fürth', '    IFK Göteborg',
       '    FC Cartagena', '    Santa Clara', '    FC Twente',
       '    Farense', '    ADO Den Haag', '    AJ Auxerre',
       '    Al Fateh', '    Valenciennes FC',
       '    Hokkaido Consadole Sapporo', '    FC St. Pauli',
       '    Albacete BP', '    1. FC Kaiserslautern', '    Al Fayha',
       '    Incheon United FC', '    KV Mechelen', '    Pohang Steelers',
       '    CD Nacional', '    Unión La Calera', '    BB Erzurumspor',
       '    Kashima Antlers', '    Arsenal de Sarandí',
       '    HJK Helsinki', '    Karlsruher SC', '    Aarhus GF',
       '    FC Zürich', '    Barcelona Sporting Club',
       '    SG Dynamo Dresden', '    Sanfrecce Hiroshima', '    Al Raed',
       '    SD Ponferradina', '    Brøndby IF', '    Lechia Gdańsk',
       '    FC Viitorul', '    SK Sturm Graz', '    IF Elfsborg',
       '    Gangwon FC', '    Melgar FBC', '    Club Atlético Grau',
       '    Jagiellonia Białystok', '    Waasland-Beveren',
       '    VfL Osnabrück', '    Nagoya Grampus', '    CF Fuenlabrada',
       '    Shamrock Rovers', '    Shimizu S-Pulse', '    RKC Waalwijk',
       '    Vålerenga Fotball', '    Clermont Foot 63',
       '    FC Ingolstadt 04', '    FC Würzburger Kickers',
       '    Górnik Zabrze', '    Charlton Athletic', '    Beerschot AC',
       '    Coquimbo Unido', '    Viktoria Köln', '    Hull City',
       '    Málaga CF', '    FC Nordsjælland', '    UD Las Palmas',
       '    VVV-Venlo', '    GwangJu FC',
       '    Chamois Niortais Football Club', '    FC Lugano',
       '    Cusco FC', '    Sparta Rotterdam', '    Sol de América',
       '    PEC Zwolle', '    Pogoń Szczecin', '    Doncaster Rovers',
       '    Kristiansund BK', '    Liverpool Fútbol Club',
       '    Club Bolívar', '    Urawa Red Diamonds', '    SK Brann',
       '    Eintracht Braunschweig', '    Nacional Asunción',
       '    Melbourne Victory', '    Kilmarnock', '    Dundalk',
       '    SSV Jahn Regensburg', '    Abha Club',
       '    Club Atlético Tigre', '    Suwon Samsung Bluewings',
       '    Shonan Bellmare', '    SD Aucas', '    Emelec',
       '    Fortuna Sittard', '    La Berrichonne de Châteauroux',
       '    Śląsk Wrocław', '    Coventry City', '    Sunderland',
       '    Alianza Lima', '    Hammarby IF', '    Cracovia',
       '    CE Sabadell FC', '    Oita Trinita', '    BK Häcken',
       '    Luton Town', '    Le Havre AC', '    IK Sirius',
       '    Zagłębie Lubin', '    Grenoble Foot 38', '    Macarthur FC',
       '    Rodez Aveyron Football', '    Vegalta Sendai',
       '    Motherwell', '    SV Wehen Wiesbaden', '    Audax Italiano',
       '    Gaz Metan Mediaş', '    Portsmouth', '    Hibernian',
       '    Always Ready', '    UD Logroñés', '    FC Voluntari',
       '    FC Hermannstadt', '    AS Nancy Lorraine',
       '    Rotherham United', '    Fleetwood Town',
       '    Jorge Wilstermann', '    Odense Boldklub', '    MSV Duisburg',
       '    FC Sochaux-Montbéliard', '    Milton Keynes Dons',
       '    River Plate Montevideo', '    Delfín SC',
       '    Universidad Católica del Ecuador', '    Deportivo Pasto',
       '    KV Oostende', '    Club Plaza Colonia', '    Wigan Athletic',
       '    FC Botoşani', '    C.D. Castellón', '    SCR Altach',
       '    Örebro SK', '    TSV Hartberg', '    Stabæk Fotball',
       '    Wycombe Wanderers', '    St. Johnstone FC',
       '    Oxford United', '    Lincoln City', '    Randers FC',
       '    Viking FK', '    FC Chambly Oise', '    Dundee United',
       '    Oriente Petrolero', '    Odds BK', '    Nacional Potosí',
       '    Sepsi OSK', '    FC Hansa Rostock', '    Lyngby BK',
       '    SpVgg Unterhaching', '    Brisbane Roar', '    Seongnam FC',
       '    SV Ried', '    CD Huachipato', '    WSG Tirol',
       '    Podbeskidzie Bielsko-Biała', '    Peterborough United',
       '    Club Blooming', '    Wisła Płock', '    Busan IPark',
       '    FSV Zwickau', '    Mjøndalen IF', '    Vejle Boldklub',
       '    Pau FC', '    FC Lausanne-Sport', '    Estudiantes de Mérida',
       '    Sagan Tosu', '    SV Waldhof Mannheim', '    Sport Huancayo',
       '    Hallescher FC', '    Kalmar FF', '    St. Mirren',
       '    SKN St. Pölten', '    Sarpsborg 08 FF', '    Shrewsbury',
       '    TSV 1860 München', '    SV Meppen', '    Ipswich Town',
       '    IK Start', '    Adelaide United', '    Stal Mielec',
       '    Centro Atlético Fénix', '    Newcastle Jets',
       '    Livingston FC', '    AC Mineros de Guayana',
       '    AFC Wimbledon', '    Burton Albion', '    Al Adalah',
       '    Warta Poznań', '    USL Dunkerque', '    Bristol Rovers',
       '    UTA Arad', '    Östersunds FK', '    Sportivo Luqueño',
       '    Politehnica Iaşi', '    Salford City',
       '    Central Coast Mariners', '    Caracas FC', '    AC Horsens',
       '    Plymouth Argyle', '    Aalesunds FK', '    Crewe Alexandra',
       '    Chindia Târgovişte', '    Oldham Athletic', '    Yokohama FC',
       '    Blackpool', '    Northampton Town', '    Bayern München II',
       '    FK Haugesund', '    KFC Uerdingen 05',
       '    Forest Green Rovers', '    Cheltenham Town',
       '    Strømsgodset IF', '    Mjällby AIF', '    Exeter City',
       '    Cambridge United', '    Grimsby Town', '    FC Vaduz',
       '    Türkgücü München', '    VfB Lübeck', '    Bolton Wanderers',
       '    Bradford City', '    1. FC Magdeburg',
       '    FC Admira Wacker Mödling', '    Hamilton Academical FC',
       '    Aragua FC', '    Accrington Stanley', '    Swindon Town',
       '    Carlisle United', '    FC Argeș', '    Port Vale',
       '    Academica Clinceni', '    Rochdale', '    Gillingham',
       '    Tranmere Rovers', '    Southend United',
       '    1. FC Saarbrücken', '    Colchester United',
       '    Mansfield Town', '    Falkenbergs FF', '    SC Verl',
       '    Varbergs BoIS', '    Crawley Town', '    Sandefjord Fotball',
       '    Newport County', '    Bohemian FC', '    Ross County FC',
       '    Scunthorpe United', '    Morecambe', '    Walsall',
       '    Leyton Orient', '    Stevenage', '    Barrow',
       '    Derry City', '    Llaneros de Guanare', '    Sligo Rovers',
       '    Zamora FC', "    St. Patrick's Athletic", '    Cork City',
       '    Shelbourne FC', '    Harrogate Town', '    Waterford FC',
       '    Finn Harps'], dtype=object)

In [55]:
# Replace digits attached to club names with empty string
df["Club"] = df["Club"].str.replace(r'\d+', '', regex=True)

# Replace dots attached to club names with empty string
df["Club"] = df["Club"].str.replace(r'. ', '', regex=True)

# Remove the leading and trailing characters (spaces, tabs, etc.)
df["Club"] = df["Club"].str.strip()

# Assessing the impact of the changes
df["Club"].sample(5)

4983          Guadalajara
11698    Waasland-Beveren
16788            Sassuolo
5037               MalmFF
314              SBenfica
Name: Club, dtype: object

#### Value, Wage and Release Clause Features:

In [56]:
# Check datatype
data_type = df[["Value", "Wage","Release Clause"]].dtypes

# Print datatype
print(f"\nThe datatypes are:")

print(data_type)

# Assessing values within the features
random_rows = df[["Value", "Wage","Release Clause"]].sample(10)

# Print
print(f"\n{random_rows}")

The datatypes are:
Value             object
Wage              object
Release Clause    object
dtype: object

       Value  Wage Release Clause
13098  €975K   €6K             €0
7035   €1.4M   €5K          €1.5M
7779   €1.7M   €5K          €1.8M
10626  €825K   €3K          €953K
7949   €1.3M   €8K          €1.2M
18551  €210K   €5K          €278K
10048  €675K   €3K          €1.1M
6905     €1M  €550          €1.6M
13640  €875K   €2K          €878K
18786  €150K  €500          €221K

These features contain monetary values, currently in object dtype, and require conversion to numerical dtype for analysis. To achieve this, we need to:

*  Remove the euro symbol (€) from the values
*  Remove the thousand separator ('k') and multiply the values by 1000
   to convert to the correct scale.

In [57]:
# Remove the euro symbol (€)
df["Value"] = df["Value"].map(lambda x: x.replace("€", ""))

df["Wage"] = df["Wage"].map(lambda x: x.replace("€", ""))

df["Release Clause"] = df["Release Clause"].map(lambda x: x.replace("€", ""))

# Assessing the update
df[["Value", "Wage","Release Clause"]]

        Value  Wage Release Clause
0      103.5M  560K         138.4M
1         63M  220K          75.9M
2        120M  125K         159.4M
3        129M  370K           161M
4        132M  270K         166.5M
...       ...   ...            ...
18974    100K    1K            70K
18975    130K   500           165K
18976    120K   500           131K
18977    100K    2K            88K
18978    100K    1K            79K

[18979 rows x 3 columns]

In [58]:
 # Function to convert monetary values to numerical
def convert_to_numeric(value, t = 1000, m = 1000000, b = 1000000000):
  """
    Converts a string a numeric value, handling thousand (K), million (M), and billion (B) suffixes.

    Parameters:
    value (str): The value to convert.
    t (int, optional): The multiplier for thousand (default is 1000).
    m (int, optional): The multiplier for million (default is 1000000).
    b (int, optional): The multiplier for billion (default is 1000000000).

    Returns:
    float: The converted numeric value.

   Notes:
   If the input is a string, it may contain a suffix (K, M, or B) indicating the scale.
   If the input is already a numeric value, it is returned unchanged.
  """

  if type(value) == str:
     if "K" in value:
        return float(value.replace("K", " "))* t
     elif "M" in value:
        return float(value.replace("M", " "))* m
     elif "B" in value:
        return float(value.replace("B", " "))* b
     else:
        return float(value)
  return value



# columns to convert
columns_to_convert = ["Value", "Wage", "Release Clause"]

# Loop through the columns
for column in columns_to_convert:

# Apply the function to the columns
  df[column] = df[column].apply(convert_to_numeric)

In [59]:
# Verifying the effectiveness of the updates
df[["Value", "Wage", "Release Clause"]].dtypes

Value             float64
Wage              float64
Release Clause    float64
dtype: object

In [60]:
# Properly insert the euro symbol (€) into the column header
df = df.rename(columns={"Value": "Value(€)", "Wage": "Wage(€)", "Release Clause": "Release Clause(€)"})

# Assessing the impact of the changes
df[["Value(€)", "Wage(€)", "Release Clause(€)"]].sample(5)

        Value(€)  Wage(€)  Release Clause(€)
441   24000000.0  31000.0         35900000.0
4207    650000.0   6000.0          1300000.0
6226   1700000.0   6000.0          1900000.0
5234   1300000.0   8000.0          2900000.0
9771   1400000.0   2000.0          1100000.0

#### IR  Feature:
This column actually represents player ratings or rankings, with the number of stars (★) indicating the level of performance.

In [61]:
df["IR"].unique()

array(['5 ★', '3 ★', '4 ★', '2 ★', '1 ★'], dtype=object)

The column contains player ratings in the format of '★', and we need to remove the ★ symbol from the values, leaving only the numerical rating.

In [62]:
# Remove ★
df["IR"] = df["IR"].str.replace("★", " ").astype(int)

# Display 10 random values
df["IR"].sample(10)

5220     1
8015     1
12933    1
898      2
481      2
2401     1
5256     1
15254    1
1895     1
6415     1
Name: IR, dtype: int64

#### Name Feature:

In [63]:
# First 5 names
df["Name"].head()

0                    Lionel Messi
1    C. Ronaldo dos Santos Aveiro
2                       Jan Oblak
3                 Kevin De Bruyne
4      Neymar da Silva Santos Jr.
Name: Name, dtype: object

In [64]:
# Capitalizes the first letter of each name
df["Name"] = df["Name"].str.title()

# Verying the update
df["Name"].head()

0                    Lionel Messi
1    C. Ronaldo Dos Santos Aveiro
2                       Jan Oblak
3                 Kevin De Bruyne
4      Neymar Da Silva Santos Jr.
Name: Name, dtype: object

#### Contract Feature:

In [65]:
# Unique values in Contract feature
df["Contract"].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 2028',
       '2010 ~ 2023', '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026',
       '2012 ~ 2025', '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027',
       '2013 ~ 2025', 'Dec 31, 2020 On Loan', '2019 ~ 2020',
       '2011 ~ 2025', '2016 ~ 2020', '2007 ~ 2021', '2020 ~ 2026',
       '2010 ~ 2025', '2009 ~ 2023', '2008 ~ 2021', '2020 ~ 2020',
       '2016 ~ 2026', 'Jan 30, 2021 On Loan', '2012 ~ 2020',
       '2014 ~ 2025', 'Jun 30, 2022 On Loan', '2015 ~ 2020',
       'May 31, 2021 On Loan', '2018 ~ 2020', '2014 ~ 2020',
       '2013 ~ 2020', '2006 ~ 2024', 'Jul 5, 2021 On Loan',
       'Dec 31, 2021 On Loan', '2004 ~ 2025', '2011 ~ 2020',
       'Jul 1, 2021 On Loan', 'Jan 1, 2021 On Loan', '2006 ~ 2023',
       'Aug 31, 2021 On Loan', '2006 ~ 2021', '2005 ~ 2023',
       '2003 ~ 2020', '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020',
       '2005 ~ 2022', 'Jan 31, 2021 On Loan', '2010 ~ 2020',
       'Dec 30, 2021 On Loan', '2008 ~ 2020', '2007 ~ 2020',
       '2003 ~ 2021', 'Jun 23, 2021 On Loan', 'Jan 3, 2021 On Loan',
       'Nov 27, 2021 On Loan', '2002 ~ 2021', 'Jan 17, 2021 On Loan',
       'Jun 30, 2023 On Loan', '1998 ~ 2021', '2003 ~ 2022',
       '2007 ~ 2023', 'Jul 31, 2021 On Loan', 'Nov 22, 2020 On Loan',
       'May 31, 2022 On Loan', '2006 ~ 2020', 'Dec 30, 2020 On Loan',
       '2007 ~ 2025', 'Jan 4, 2021 On Loan', 'Nov 30, 2020 On Loan',
       '2004 ~ 2020', '2009 ~ 2025', 'Aug 1, 2021 On Loan'], dtype=object)

The column, intended to display only the end years of contracts, contains additional information, with some entries denoted as "on loan" for players on loan and "free" for players on a free transfer, as well as different date formats, requiring data cleaning and preprocessing to extract the relevant contract years.

In [66]:
# Retrive rows in the contract column that contains "On Loan"
loan_rows = df[df["Contract"].str.contains("On Loan")]
loan_rows

,ID,Name,Nationality,Age,Overall_Rating,Potential_Rating,Club,Contract,Positions,Height(cm),...,Attack_Willingness,D/W,IR,Passing,SHO,PAS,Dribbling,Defending,Physicality,Hits
205,173731,Gareth Bale,Wales,30,83,83,TottenhaHotspur,"Jun 30, 2021 On Loan",RW,185,...,Medium,Medium,4,88,84,82,80,58,73,0
248,193105,Alphonse Areola,France,27,82,86,Fulham,"Jun 30, 2021 On Loan",GK,195,...,Medium,Medium,2,85,79,80,84,55,78,0
254,200888,Danilo Luís Hélio Pereira,Portugal,28,82,82,PariSaint-Germain,"Jun 30, 2021 On Loan","CDM, CM",188,...,Medium,High,3,66,63,72,73,80,85,0
302,216409,Matteo Politano,Italy,26,81,81,Napoli,"Jun 30, 2021 On Loan","RM, RW, ST",171,...,High,Medium,2,83,77,78,84,42,55,0
306,223959,Lucas Torreira,Uruguay,24,81,85,AtléticMadrid,"Jun 30, 2021 On Loan","CDM, CM",166,...,Medium,High,2,74,67,75,79,79,74,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18472,242601,Moudi Najjar,Australia,20,52,65,MacarthuFC,"Aug 31, 2021 On Loan",ST,182,...,High,Low,1,67,51,39,53,21,52,0
18571,236818,Arthur Read,England,20,51,63,Stevenage,"Jun 30, 2021 On Loan","CM, RW, LW",178,...,Medium,Medium,1,57,45,52,59,38,48,0
18600,240392,Yubiao Deng,China PR,23,51,60,ShijiazhuanEveBrighF.C.,"Dec 31, 2020 On Loan",CM,181,...,Medium,Medium,1,71,42,52,54,47,52,0
18622,252516,Pu Chen,China PR,23,51,60,ShijiazhuanEveBrighF.C.,"Dec 31, 2020 On Loan","CAM, LM",177,...,Medium,Medium,1,59,41,55,49,34,47,0
18680,232888,Zhechao Chen,China PR,25,51,56,GuangzhoR&FC,"Dec 31, 2020 On Loan","CM, LM, LB",177,...,Medium,Medium,1,61,35,49,50,59,58,0

1013 players are on loan

In [67]:
#Retrive rows in the contract column that contains "Free"
free_rows = df[df["Contract"].str.contains("Free")]
free_rows

,ID,Name,Nationality,Age,Overall_Rating,Potential_Rating,Club,Contract,Positions,Height(cm),...,Attack_Willingness,D/W,IR,Passing,SHO,PAS,Dribbling,Defending,Physicality,Hits
289,230347,Welington Kauê Dano Nascimento,Brazil,20,81,81,NClub,Free,"LB, LM",178,...,Medium,Medium,1,79,54,76,78,75,74,0
292,230225,Juan Everton Mestres De Mesquita,Brazil,24,81,81,NClub,Free,"CB, CDM",181,...,High,Medium,1,71,61,57,62,82,80,0
369,245299,Jaime Nicolás Frendado,Uruguay,36,80,80,NClub,Free,"CB, CDM",181,...,High,Medium,1,71,61,57,62,82,75,0
374,245294,Jorge Ezequiel Serendero,Uruguay,32,80,80,NClub,Free,GK,190,...,Medium,Medium,1,78,81,77,77,42,80,0
375,245308,Mauro Evidio Nérez,Uruguay,32,80,80,NClub,Free,"LB, LM",178,...,Medium,Medium,1,79,54,75,78,76,74,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17220,247059,Ali Al Hidhani,United Arab Emirates,22,56,64,NClub,Free,RB,172,...,Medium,Medium,1,73,33,45,55,51,55,0
17343,251734,Anudaan Sanghu,India,20,56,56,NClub,Free,"RM, CM",168,...,Medium,Low,1,79,42,50,59,29,49,0
17659,251738,Madanapal Chada,India,27,55,55,NClub,Free,ST,178,...,High,Medium,1,67,52,47,61,32,57,0
17661,251741,Eelamynthan Suresh,India,28,55,55,NClub,Free,"RM, CAM, RB",175,...,High,Medium,1,73,49,51,54,41,70,0
18205,251737,Jagatjiva Mangat,India,26,53,54,NClub,Free,LM,171,...,Medium,Medium,1,68,41,45,58,22,41,0

237 players are on free transfer

In [ ]:
df[["Contract", "Joined"]].sample(5)

                   Contract        Joined
6368            2019 ~ 2024   Jul 1, 2019
5792            2009 ~ 2020   Jan 1, 2009
17002           2019 ~ 2021   Jul 1, 2019
1884   Jun 30, 2021 On Loan   Jan 2, 2019
10394           2019 ~ 2023  Feb 24, 2019

We have to:

* Create new Status columns which returns True for players "On Loan" and vice-versa
* We will do same for players on "Free" transfer.
* Remove "On Loan" and "Free" information from the Contract column.
* Modify the Contract column into Contarct End Date.

In [68]:
def player_status(x):
  """
    Determine if a player was on loan transfer.

    Parameters:
    x (str): The contract information.

    Returns:
    bool: True if the player was signed on loan, False otherwise.
"""
  if "On Loan" in x:
      return True
  else:
      return False

# Apply the function to the Contract column to create the Player_on_Loan column
df["Player_on_Loan"] = df["Contract"].apply(player_status)

In [ ]:
df[["Contract", "Player_on_Loan"]].sample(15)

                   Contract  Player_on_Loan
6687            2019 ~ 2024           False
3019            2019 ~ 2021           False
1752            2018 ~ 2023           False
10707           2016 ~ 2022           False
4924            2010 ~ 2021           False
1676            2018 ~ 2022           False
1292            2018 ~ 2021           False
2729            2017 ~ 2022           False
17088           2018 ~ 2023           False
16029  Jun 30, 2021 On Loan            True
14113           2020 ~ 2022           False
8470   Jun 30, 2021 On Loan            True
3845            2020 ~ 2021           False
4737            2014 ~ 2021           False
12154           2014 ~ 2020           False

In [69]:
def free_transfer(x):
  """
    Determine if a player was signed on a free transfer.

    Parameters:
    x (str): The contract information.

    Returns:
    bool: True if the player was signed on a free transfer, False otherwise.
"""
  if "Free" in x:
        return True
  else:
        return False

# Apply the function to the Contract column to create the Player_on_Loan column
df["Free_transfer"] = df["Contract"].apply(free_transfer)

In [ ]:
df[["Contract", "Free_transfer"]].sample(10)

          Contract  Free_transfer
842    2019 ~ 2021          False
11616  2019 ~ 2024          False
511    2017 ~ 2022          False
9901   2015 ~ 2022          False
14952         Free           True
16950  2019 ~ 2022          False
11779  2019 ~ 2021          False
3904   2020 ~ 2023          False
16611  2019 ~ 2021          False
5903   2020 ~ 2025          False

In [ ]:
# Remove On Loan and free string from contract column
df["Contract"]  = df["Contract"].str.replace("On Loan","")

df["Contract"]  = df["Contract"].str.replace("Free","")

# Verifying the update
df["Contract"].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 ', '2009 ~ 2021',
       '2019 ~ 2021', '2019 ~ 2026', '', '2012 ~ 2028', '2010 ~ 2023',
       '2014 ~ 2021', '2015 ~ 2025', '2014 ~ 2026', '2012 ~ 2025',
       '2017 ~ 2020', '2002 ~ 2022', '2020 ~ 2027', '2013 ~ 2025',
       'Dec 31, 2020 ', '2019 ~ 2020', '2011 ~ 2025', '2016 ~ 2020',
       '2007 ~ 2021', '2020 ~ 2026', '2010 ~ 2025', '2009 ~ 2023',
       '2008 ~ 2021', '2020 ~ 2020', '2016 ~ 2026', 'Jan 30, 2021 ',
       '2012 ~ 2020', '2014 ~ 2025', 'Jun 30, 2022 ', '2015 ~ 2020',
       'May 31, 2021 ', '2018 ~ 2020', '2014 ~ 2020', '2013 ~ 2020',
       '2006 ~ 2024', 'Jul 5, 2021 ', 'Dec 31, 2021 ', '2004 ~ 2025',
       '2011 ~ 2020', 'Jul 1, 2021 ', 'Jan 1, 2021 ', '2006 ~ 2023',
       'Aug 31, 2021 ', '2006 ~ 2021', '2005 ~ 2023', '2003 ~ 2020',
       '2009 ~ 2020', '2002 ~ 2020', '2005 ~ 2020', '2005 ~ 2022',
       'Jan 31, 2021 ', '2010 ~ 2020', 'Dec 30, 2021 ', '2008 ~ 2020',
       '2007 ~ 2020', '2003 ~ 2021', 'Jun 23, 2021 ', 'Jan 3, 2021 ',
       'Nov 27, 2021 ', '2002 ~ 2021', 'Jan 17, 2021 ', 'Jun 30, 2023 ',
       '1998 ~ 2021', '2003 ~ 2022', '2007 ~ 2023', 'Jul 31, 2021 ',
       'Nov 22, 2020 ', 'May 31, 2022 ', '2006 ~ 2020', 'Dec 30, 2020 ',
       '2007 ~ 2025', 'Jan 4, 2021 ', 'Nov 30, 2020 ', '2004 ~ 2020',
       '2009 ~ 2025', 'Aug 1, 2021 '], dtype=object)

The Contract feature was meant to show contract duration (end year), but has inconsistent formatting. However, some rows incorrectly include the day and month.

In [75]:
# Function to clean the Contract column
def clean_contract(date_str):
   """
   Cleans a date string by removing month, day, and unnecessary characters.

   Parameters:
   date_str (str): The input date string to be cleaned.

   Returns:
   str: The cleaned date string with only the year remaining
   """
    # Remove month and date
   date_str = re.sub(r'[A-Za-z]+\s+\d{1,2},\s+', '', date_str)
    # Keep only the year before the ~ symbol
   date_str = re.sub(r'\s*~\s*\d{4}', '', date_str)
   return date_str.strip()

# Apply the function to the date column
df["Contract_End_Date"] = df["Contract"].apply(clean_contract)

In [76]:
df['Contract_End_Date'].sample(10)

18526            2016
9308     2021 On Loan
11386            2020
15047    2021 On Loan
1359             2019
14549            2020
18027            2019
967              2011
7844             2018
5365             Free
Name: Contract_End_Date, dtype: object

In [77]:
# Drop Contract column
df = df.drop(columns=["Contract"])

In [ ]:
# first 10 rows
df.head(10)

,ID,Name,Nationality,Age,Overall_Rating,Potential_Rating,Club,Positions,Height(cm),Weight(kg),...,Passing,SHO,PAS,Dribbling,Defending,Physicality,Hits,Player_on_Loan,Free_transfer,Contract_Year_End
0,158023,Lionel Messi,Argentina,33,93,93,FBarcelona,"RW, ST, CF",170,72,...,85,92,91,95,38,65,0,False,False,2004
1,20801,C. Ronaldo Dos Santos Aveiro,Portugal,35,92,92,Juventus,"ST, LW",187,83,...,89,93,81,89,35,77,0,False,False,2018
2,200389,Jan Oblak,Slovenia,27,91,93,AtléticMadrid,GK,188,87,...,87,92,78,90,52,90,0,False,False,2014
3,192985,Kevin De Bruyne,Belgium,29,91,91,ManchesteCity,"CAM, CM",181,70,...,76,86,93,88,64,78,0,False,False,2015
4,190871,Neymar Da Silva Santos Jr.,Brazil,28,91,91,PariSaint-Germain,"LW, CAM",175,68,...,91,85,86,94,36,59,0,False,False,2017
5,188545,Robert Lewandowski,Poland,31,91,91,FBayerMünchen,ST,184,80,...,78,91,78,85,43,82,0,False,False,2014
6,209331,Mohamed Salah,Egypt,28,90,90,Liverpool,RW,175,71,...,93,86,81,90,45,75,0,False,False,2017
7,212831,Alisson Ramses Becker,Brazil,27,90,91,Liverpool,GK,191,91,...,86,88,85,89,51,91,0,False,False,2018
8,231747,Kylian Mbappé,France,21,90,95,PariSaint-Germain,"ST, LW, RW",178,73,...,96,86,78,91,39,76,1600,False,False,2018
9,192448,Marc-André Ter Stegen,Germany,28,90,93,FBarcelona,GK,187,85,...,88,85,88,90,45,88,0,False,False,2014

In [ ]:
# first 10 last rows
df.tail(10)

,ID,Name,Nationality,Age,Overall_Rating,Potential_Rating,Club,Positions,Height(cm),Weight(kg),...,Passing,SHO,PAS,Dribbling,Defending,Physicality,Hits,Player_on_Loan,Free_transfer,Contract_Year_End
18969,257936,Yue Song,China PR,28,47,47,TianjiTEDFC,CM,185,79,...,65,37,49,46,40,59,0,False,False,2020
18970,257689,Huapeng Wang,China PR,20,47,53,GuangzhoR&FC,CB,181,77,...,59,22,25,30,47,55,0,False,False,2020
18971,255958,Mateo Flores,Bolivia,19,47,63,CluBolívar,CDM,174,68,...,57,32,43,48,44,49,0,False,False,2020
18972,257710,Mengxuan Zhang,China PR,21,47,52,ChongqinDangdaLifaFSWTeam,CB,177,70,...,58,23,26,27,50,48,0,False,False,2020
18973,258736,Vani Da Silva,England,17,47,67,OldhaAthletic,ST,171,58,...,70,46,40,53,16,40,0,False,False,2020
18974,247223,Ao Xia,China PR,21,47,55,WuhaZall,CB,178,66,...,64,28,26,38,48,51,0,False,False,2018
18975,258760,Ben Hough,England,17,47,67,OldhaAthletic,CM,175,65,...,64,40,48,49,35,45,0,False,False,2020
18976,252757,Ronan Mckinley,England,18,47,65,DerrCity,CM,179,74,...,63,39,44,46,40,53,0,False,False,2019
18977,243790,Zhen'Ao Wang,China PR,20,47,57,DaliaYiFanFC,RW,175,69,...,58,49,41,49,30,44,0,False,False,2020
18978,252520,Xiao Zhou,China PR,21,47,57,DaliaYiFanFC,"CB, LB",188,75,...,62,22,39,42,45,55,0,False,False,2019